FROM ubuntu:16.04

RUN apt-get update && apt-get -qq -y install curl libssl-dev build-essential pkg-config git python cmake
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-2017-11-06
